### ISSUE TITLE
Lỗi kết xuất với chữ ký (do xử lý sai ở đâu đó)

### ISSUE THREAD

**Issue by Cocochi** [Cocochi/gcollector#77]
Hiện tại đang bị lỗi trên log của server kiêm tra lại và fix lỗi
Thu Jul 16 2015 16:43:37 GMT+0700 (SE Asia Standard Time)uncaughtException: Error: ENOENT, no such file or directory 'C:\MobiWork\Portal\public\exports\559493b065fe9c3820914f82\55a77cc96c79beb8024dc3e4\tuan_kiem_55a764f26c79beb8024dc33d\Photo\55a772436c79beb8024dc3a6\chu_ky\http:\image.mobiwork.vn\Files\559493b065fe9c3820914f82\55a772436c79beb8024dc3a6\sign_chu_ky.jpg'
    at Object.fs.openSync (fs.js:439:18)
    at Object.fs.writeFileSync (fs.js:978:15)
    at convertObjRecords (C:\MobiWork\gInspector_Services\collection_provider\ExportsProvider.js:762:48)
    at C:\MobiWork\gInspector_Services\collection_provider\ExportsProvider.js:683:33
    at C:\MobiWork\gInspector_Services\node_modules\mongodb\lib\mongodb\cursor.js:172:16
    at commandHandler (C:\MobiWork\gInspector_Services\node_modules\mongodb\lib\mongodb\cursor.js:720:16)
    at b (domain.js:183:18)
    at C:\MobiWork\gInspector_Services\node_modules\mongodb\lib\mongodb\db.js:1878:9
    at b (domain.js:183:18)
    at Server.Base._callHandler (C:\MobiWork\gInspector_Services\node_modules\mongodb\lib\mongodb\connection\base.js:453:41)

**Comment by Cocochi** [comment]
Done
